# Generated by Django 5.0.6 on 2024-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profiledetails_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='sate_name',
            field=models.CharField(max_length=100),
        ),
    ]
