# Generated by Django 5.0.6 on 2024-07-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_order', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place_order',
            old_name='product',
            new_name='Product',
        ),
    ]
