# Generated by Django 5.0.6 on 2024-07-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_order', '0004_rename_product_place_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_order',
            name='Stats',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Accepted ', 'Accepted'), ('Packed', 'Packed'), ('On the Way', 'On the Way')], default='Pending', max_length=100),
        ),
    ]
