# Generated by Django 5.0.6 on 2024-06-07 07:16

import autoslug.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('udid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now=True)),
                ('upate_date_by', models.DateField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('slugField', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='category_name', unique=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('udid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now=True)),
                ('upate_date_by', models.DateField(auto_now_add=True)),
                ('subcategory_name', models.CharField(max_length=100, unique=True)),
                ('slugField', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='subcategory_name', unique=True)),
                ('subcategory_image', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('udid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now=True)),
                ('upate_date_by', models.DateField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('slugField', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='product_name', unique=True)),
                ('product_price', models.IntegerField()),
                ('product_decribstion', models.TextField()),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='project.category')),
                ('product_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='project.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('udid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now=True)),
                ('upate_date_by', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='project.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
