# Generated by Django 5.0.6 on 2024-06-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_color_variations_color_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Size',
            field=models.ManyToManyField(blank=True, to='project.size_variations'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cat', to='project.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.ManyToManyField(blank=True, to='project.color_variations'),
        ),
    ]
