# Generated by Django 5.0.6 on 2024-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_product_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory'),
        ),
    ]
