# Generated by Django 5.0.6 on 2024-06-13 09:37

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_subcategory_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='slugField',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['product_name', 'product_Brand', 'product_artical'], unique=True),
        ),
    ]
