# Generated by Django 5.0.6 on 2024-07-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_product_slugfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_dicount',
            field=models.IntegerField(default=20),
        ),
    ]
